services:
  z-ui:
    build:
      context: .
      dockerfile: Dockerfile
    image: z-ui:dev
    container_name: z-ui-dev
    hostname: "z-ui-dev"
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./db:/app/db
      - ./cert:/app/cert
    cap_add:
      - NET_ADMIN
