services:
  z-ui:
    image: ghcr.io/zendan-ui/z-ui:latest
    container_name: z-ui
    restart: unless-stopped
    network_mode: host
    env_file: .env
    volumes:
      - /var/lib/z-ui:/var/lib/z-ui
    cap_add:
      - NET_ADMIN
