services:
  z-ui:
    image: ghcr.io/zendan-ui/z-ui:latest
    container_name: z-ui
    hostname: "z-ui"
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./db:/app/db
      - ./cert:/app/cert
    cap_add:
      - NET_ADMIN
